name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag texlive-full:test
    - name: Execute TeX
      run: docker run texlive-full:test tex -version
